require 'faker'
require_all 'app'

owner1 = Owner.create(name: Faker::Name.name, username: Faker::Name.unique.name)
owner2 = Owner.create(name: Faker::Name.name, username: Faker::Name.unique.name)
owner3 = Owner.create(name: Faker::Name.name, username: Faker::Name.unique.name)
owner4 = Owner.create(name: Faker::Name.name, username: Faker::Name.unique.name)
owner5 = Owner.create(name: Faker::Name.name, username: Faker::Name.unique.name)
owner6 = Owner.create(name: Faker::Name.name, username: Faker::Name.unique.name)
owner7 = Owner.create(name: Faker::Name.name, username: Faker::Name.unique.name)
owner8 = Owner.create(name: Faker::Name.name, username: Faker::Name.unique.name)
owner9 = Owner.create(name: Faker::Name.name, username: Faker::Name.unique.name)
owner10 = Owner.create(name: Faker::Name.name, username: Faker::Name.unique.name)

dog1 = Dog.create(name: Faker::Dog.name, owner_id: 1)
dog2 = Dog.create(name: Faker::Dog.name, owner_id: 1)
dog3 = Dog.create(name: Faker::Dog.name, owner_id: 2)
dog4 = Dog.create(name: Faker::Dog.name, owner_id: 2)
dog5 = Dog.create(name: Faker::Dog.name, owner_id: 3)
dog6 = Dog.create(name: Faker::Dog.name, owner_id: 4)
dog7 = Dog.create(name: Faker::Dog.name, owner_id: 5)
dog8 = Dog.create(name: Faker::Dog.name, owner_id: 5)
dog9 = Dog.create(name: Faker::Dog.name, owner_id: 5)
dog10 = Dog.create(name: Faker::Dog.name, owner_id: 6)
dog11 = Dog.create(name: Faker::Dog.name, owner_id: 7)
dog12 = Dog.create(name: Faker::Dog.name, owner_id: 8)
dog13 = Dog.create(name: Faker::Dog.name, owner_id: 8)
dog14 = Dog.create(name: Faker::Dog.name, owner_id: 8)

walker1 = Walker.create(name: Faker::Name.name, small_dog_rate: Faker::Number.between(5, 15), medium_dog_rate: Faker::Number.between(10, 25), large_dog_rate: Faker::Number.between(20, 50))
walker2 = Walker.create(name: Faker::Name.name, small_dog_rate: Faker::Number.between(5, 15), medium_dog_rate: Faker::Number.between(10, 25), large_dog_rate: Faker::Number.between(20, 50))
walker3 = Walker.create(name: Faker::Name.name, small_dog_rate: Faker::Number.between(5, 15), medium_dog_rate: Faker::Number.between(10, 25), large_dog_rate: Faker::Number.between(20, 50))
walker4 = Walker.create(name: Faker::Name.name, small_dog_rate: Faker::Number.between(5, 15), medium_dog_rate: Faker::Number.between(10, 25), large_dog_rate: Faker::Number.between(20, 50))
walker5 = Walker.create(name: Faker::Name.name, small_dog_rate: Faker::Number.between(5, 15), medium_dog_rate: Faker::Number.between(10, 25), large_dog_rate: Faker::Number.between(20, 50))
walker6 = Walker.create(name: Faker::Name.name, small_dog_rate: Faker::Number.between(5, 15), medium_dog_rate: Faker::Number.between(10, 25), large_dog_rate: Faker::Number.between(20, 50))
walker7 = Walker.create(name: Faker::Name.name, small_dog_rate: Faker::Number.between(5, 15), medium_dog_rate: Faker::Number.between(10, 25), large_dog_rate: Faker::Number.between(20, 50))
walker8 = Walker.create(name: Faker::Name.name, small_dog_rate: Faker::Number.between(5, 15), medium_dog_rate: Faker::Number.between(10, 25), large_dog_rate: Faker::Number.between(20, 50))
walker9 = Walker.create(name: Faker::Name.name, small_dog_rate: Faker::Number.between(5, 15), medium_dog_rate: Faker::Number.between(10, 25), large_dog_rate: Faker::Number.between(20, 50))
walker10 = Walker.create(name: Faker::Name.name, small_dog_rate: Faker::Number.between(5, 15), medium_dog_rate: Faker::Number.between(10, 25), large_dog_rate: Faker::Number.between(20, 50))

walk1 = Walk.create(dog: dog13, walker: walker1)
walk2 = Walk.create(dog: dog1, walker: walker1)
walk3 = Walk.create(dog: dog2, walker: walker2)
walk4 = Walk.create(dog: dog3, walker: walker3)
