require 'faker'
require_all 'app'

owner1 = Owner.create(name: Faker::Name.name)
owner2 = Owner.create(name: Faker::Name.name)
owner3 = Owner.create(name: Faker::Name.name)
owner4 = Owner.create(name: Faker::Name.name)
owner5 = Owner.create(name: Faker::Name.name)
owner6 = Owner.create(name: Faker::Name.name)
owner7 = Owner.create(name: Faker::Name.name)
owner8 = Owner.create(name: Faker::Name.name)
owner9 = Owner.create(name: Faker::Name.name)
owner10 = Owner.create(name: Faker::Name.name)

dog1 = Dog.create(name: Faker::Dog.name)
dog2 = Dog.create(name: Faker::Dog.name)
dog3 = Dog.create(name: Faker::Dog.name)
dog4 = Dog.create(name: Faker::Dog.name)
dog5 = Dog.create(name: Faker::Dog.name)
dog6 = Dog.create(name: Faker::Dog.name)
dog7 = Dog.create(name: Faker::Dog.name)
dog8 = Dog.create(name: Faker::Dog.name)
dog9 = Dog.create(name: Faker::Dog.name)
dog10 = Dog.create(name: Faker::Dog.name)
dog11 = Dog.create(name: Faker::Dog.name)
dog12 = Dog.create(name: Faker::Dog.name)
dog13 = Dog.create(name: Faker::Dog.name)
dog14 = Dog.create(name: Faker::Dog.name)

walker1 = Walker.create(name: Faker::Name.name)
walker2 = Walker.create(name: Faker::Name.name)
walker3 = Walker.create(name: Faker::Name.name)
walker4 = Walker.create(name: Faker::Name.name)
walker5 = Walker.create(name: Faker::Name.name)
walker6 = Walker.create(name: Faker::Name.name)
walker7 = Walker.create(name: Faker::Name.name)
walker8 = Walker.create(name: Faker::Name.name)
walker9 = Walker.create(name: Faker::Name.name)
walker10 = Walker.create(name: Faker::Name.name)

walk1 = Walk.create(dog: dog13, walker: walker1)
walk2 = Walk.create(dog: dog1, walker: walker1)
walk3 = Walk.create(dog: dog2, walker: walker2)
walk4 = Walk.create(dog: dog3, walker: walker3)
